### PR TITLE
fix: correct the spread order for http_emitter options

### PR DESCRIPTION
**Pull request by lholmquist**
fixes: #223

I would like to add a test for this,  but I think some type definitions need to be added so typescript doesn't complain about me trying to pass in more options in the send method.  Keeping as Draft for now

Signed-off-by: Lucas Holmquist <lholmqui@redhat.com>

### CODE REVIEW

**Comment by lholmquist** [comment]
While this should be a fairly straightforward change,  i'm running into issues related to Typescript when adding in the tests.

I know basic's, but I'm not sure how to proceed when trying to declare the type for a variable object that uses the spread operator.

@grant perhaps you have some insight, since from my reading of other issues,  you were the most vocal for adding typescript support.   Thanks in advance

Also cc @lance

**Comment by grant** [comment]
That's a bad bug. Thanks for the PR!

I too have seen many TypeScript issues due to the fact this repo is half js, half ts, which causes issues with types due to inferred types.

I've added an issue here: https://github.com/cloudevents/sdk-javascript/issues/203
I'll talk about that issue there.

**Comment by lance** [comment]
I don't know. It could be a while before the rewrite lands and it might be that @c-pius may want to ref `master` for the time being? Care to chime in @c-pius?

**Comment by c-pius** [comment]
From my side there is no urgency. Anyway, thanks for your great work with CE and this SDK!

**Comment by lholmquist** [comment]
closing this since it will be fixed in #226

**Pull request closed without merging**
