### PR TITLE
gts config

### LINKED ISSUE #263: gts not found
`gts` is used in the `tsconfig.json` but isn't installed or specified in the package.json.
This raises an error for tooling.

### PR DESCRIPTION
**Pull request by grant**
Adds gts to dev deps.
Fixes #263

### CODE REVIEW

**Comment by lance** [comment]
We don't use `gts`, so I'm not sure why you are adding this.

**Comment by grant** [comment]
Yeah, I realized the error and usage of `gts` was in an `examples` folder.

https://github.com/cloudevents/sdk-javascript/blob/master/examples/typescript-ex/package.json

Do we want to use this in the future?

Feel free to close this PR.

**Comment by lance** [comment]
I don't have strong feelings either way about `gts`. I'm open to it, but haven't really looked into it.

**Comment by lance** [comment]
Closing for now. If you want to introduce `gts` usage in a PR, feel free.

**Pull request closed without merging**
