### PR TITLE
Added missing 'source' getter on Spec02

### PR DESCRIPTION
**Pull request by micheleangioni**
Hi,

on the Spec02 object a getter for the `source` attribute is missing.
The Spec01 object has it, so I added it also in the new version.

Best

### CODE REVIEW

**Comment by micheleangioni** [comment]
Tests are passing, but the `coverage` is failing.

**Comment by hechi** [comment]
hmmm... seams that the `CODADY_PROJECT_TOKEN` is not set probably @fabiojose could help us?

**Comment by fabiojose** [comment]
Hello folks! I will check that problem.

**Comment by fabiojose** [comment]
@micheleangioni, please replace the entry in `env.global` with below and push again! This entry is in `.travis.yaml`.

```yaml
secure: "GgLsminwitZCtFwRkijoF03uz0+jA+jayrWyvkFfipND8S7KkmcY6iqBjBkA/ZNkvh2jgwD3fG7Jp6f795Oyb6oq8u/xF7h446YcG4FPye1v6abWhKLaOQrcTca++xl6Ph6sHRRwaV2dw/UIRRHikJWZEIKS2jgAkQ1dW7srMJhIWTIegDYYpj3c1Ri2wL5S9799zyO/c12JLpawxQvzhEG2YyYkdEI0H/9HsUezoBrCZdxjVb/LAa0nUTmQiAfX4CYRHidU4QCbznQhHWFdGr/9wKvy1dyCxAWLosWSy+mIq3teeCJ80c/Yi+yEv96tg5wL75shfYzx4JMSL6YIyfF6OrbAM0jYGIMJdf/UEG1TKNpRnIqugnCJbdjZpn6mavrayjnaq9KSc7wgXBXox5jucfWLDfV2LZ18qfqHIeubIT7X69k8P5M4z4MU3YR3mqiZtEy6CPi+h0ReMLheFKemAmHWSL4zV1YfBRFVyFP0LM4Qsi4UVtCJQUHwvjNcO2ZUXLe6OzqXN987JKwTOyecmn9s/24UDofBxuMqTWYTssKPI0bHpOiWCqd5ml9Uz1/5o6bjGhvbJjv1K/0xWS2PoWim/RSnNTNi+en+GgEKuaDZkCktHVOKg7xkpsW0DvtcpwVQRdyXUN1s2h+EHgSBuoeAo4fhbXRUVsu5zuY="
```

**Comment by micheleangioni** [comment]
Hi @fabiojose , thanks for your answer. I have tried to do as you said (I updated the .travis.yml file), but I get the same error..

**Comment by fabiojose** [comment]
Good, let's remove the `script: npm run coverage` for now. 
Please remove the command above in `.travis.yml` and push again.

@micheleangioni  thanks for you patience.

**Comment by micheleangioni** [comment]
@fabiojose I have updated the PR :)

**Comment by cwallsfdc** [comment]
Publish this change to npm?  @fabiojose

**Pull request merged**
