### PR TITLE
Change binary http bindings to adhere to spec

### PR DESCRIPTION
**Pull request by playground-julia**
Changed content type and made optional parameters optional as detailed in the cloudevents spec.

### CODE REVIEW

**Comment by fabiojose** [comment]
@playground-julia Please check the CI, some tests are failing.

**Comment by playground-julia** [comment]
I'm going to merge changes from PR #14 with this so that the tests will pass. I'm going to close PR #14 as well because I didn't sign it.

**Comment by playground-julia** [comment]
@fabiojose tests are passing now.

Copying comments from PR #14 over. I saw line 14. I don't think it's useless because the config object is being changed in line 6/7. That's what was causing npm test to fail...

**Comment by fabiojose** [comment]
@playground-julia  Could you open an issue for registration and link this PR there?

**Comment by playground-julia** [comment]
Issued and linked!

**Pull request merged**
