### PR TITLE
Delete OLDOCS.md

### PR DESCRIPTION
**Pull request by grant**
There's no need to keep old docs around an old spec version in the master branch. Git history will keep them.

### CODE REVIEW

**Comment by grant** [comment]
Hi @fabiojose,
I request you as a reviewer until I am listed as a collaborator to this repo. Can you review this PR?
–Grant

**Comment by fabiojose** [comment]
Good for you @grant 
LGTM

**Comment by grant** [comment]
Thanks!

**Comment by grant** [comment]
Hi @fabiojose,
Can we approve and merge this? I hope to work on this library this week.

**Comment by grant** [comment]
Thanks!

**Pull request merged**
