### PR TITLE
chore: remove uuid dependency in favor of crypto package

### PR DESCRIPTION
**Pull request by lance**
## Proposed Changes

As of Node.js 14.17.0 the crypto package has a `randomUUID()` function
which we can use to replace our external dependency.

Signed-off-by: Lance Ball <lball@redhat.com>

### CODE REVIEW

**Comment by lance** [comment]
Note that this change removes support for Node.js 12.x which is not yet EOL. We may want to consider holding off on this until April 2022 when that happens.

**Comment by matthewrobertson** [comment]
I would probably wait a while after Node.js 12 goes EOL before you land this so developer have time to migrate.

**Review by grant — CHANGES_REQUESTED** [review]
As mentioned, I don't recommend removing support for Maintenance LTS versions of Node. This is a good reference, but we shouldn't remove this version from support or tests.

For example, many customers are still running Node 10 applications and haven't upgraded their Node version.

**Comment by lance** [comment]
> As mentioned, I don't recommend removing support for Maintenance LTS versions of Node. This is a good reference, but we shouldn't remove this version from support or tests.
> 
> For example, many customers are still running Node 10 applications and haven't upgraded their Node version.

Yikes! That's been EOL for a while. In any case, y'all are probably right. I was just eager to show that we don't like to carry a lot of dependencies and a willingness to remove them. :)

**Pull request closed without merging**
