### PR TITLE
fix: use es6 for cloudevents.js

### PR DESCRIPTION
**Pull request by grant**

### CODE REVIEW

**Comment by grant** [comment]
The Travis failure is not due to changes in this PR.

**Comment by grant** [comment]
Yes, I'd like to get there too, but I don't want to change the whole codebase by renaming methods at this point.

I'd like to merge this incremental improvement and make small PRs. Right now I can't even make simple changes due to Travis configs and DCO checks which makes things painful.

**Comment by lance** [comment]
@grant you should rebase from `master` to pull in the Travis-CI code coverage fix. That will re-run the tests and you'll see a successful build.

**Comment by grant** [comment]
I think the PR Quality Review tool is actually wrong here. It's saying an object is a block.

**Comment by lance** [comment]
@grant I agree - the Codacy rule seems broken.

**Pull request merged**
