### PR TITLE
Use const instead of let where applicable

### PR DESCRIPTION
**Pull request by danbev**
Signed-off-by: Daniel Bevenius <daniel.bevenius@gmail.com>

### CODE REVIEW

**Comment by lance** [comment]
@danbev just FYI, most if not all of these changes are captured in https://github.com/cloudevents/sdk-javascript/pull/55

**Comment by danbev** [comment]
@lance I'll double check these changes once #55 lands and close this pr if everything is covered.

**Comment by grant** [comment]
Looks like there are conflicts.

**Comment by fabiojose** [comment]
@danbev fix the conflicts, please.

**Comment by danbev** [comment]
All of the these were taken care of by #55 so I'm closing this.

**Pull request closed without merging**
