### PR TITLE
backport(v3.2.x) onto the v3.x branch 

### PR DESCRIPTION
**Pull request by lance**
## Proposed Changes

- This is a backport PR including all non-breaking changes since 3.1.0 

We're landing breaking changes on `main` at the moment, so if we want to eventually do a 3.2.x release, we need to branch at https://github.com/cloudevents/sdk-javascript/commit/f3953a9a5abf5c0267247f9939cf567a47eccd91. We'll probably want to backport the following PR and commits before a release.

- https://github.com/cloudevents/sdk-javascript/pull/328 
- https://github.com/cloudevents/sdk-javascript/commit/4779d89ad054973cb0af8ec4119e073b78970392
- https://github.com/cloudevents/sdk-javascript/commit/7423acb7fc4d431cc8d335fd5ccb1ad4a1f28a65

- Version: Pending 3.2.0

```console
❯ git log v3.x..v3.2.x-backport --oneline
```
d8df5ef (HEAD -> v3.2.x-backport, origin/v3.2.x-backport) chore(example): Replaced body parser with express JSON parser (#334)
719c2f0 fix: upgrade cloudevents from 3.0.1 to 3.1.0 (#335)
ae21dba feat: add a constructor parameter for loose validation (#328)
08e98c7 feat: introduce Message, Serializer, Deserializer and Binding interfaces (#324)
17d4bc8 chore: add cucumber.js to list of files to lint and /docs to .gitignore (#327)
73f0bec chore: Update README with correct links for the support specification versions (#321)
0adcc35 chore: Remove commented version import. (#319)
6e2390e fix: upgrade uuid from 8.2.0 to 8.3.0 (#317)
4bf2eb8 chore: Update references of master to main (#316)
b5cf886 test: implement pending tests leftover from TS rewrite (#315)
8ac3eb0 refactor: validate cloudevent version agnostic (#311)
81623ac chore: typo (#313)
b3624c2 docs: add ref to CoC and other things (#244)

### CODE REVIEW

**Review by grant — APPROVED** [review]

**Comment by lance** [comment]
Can't quite figure out why DCO check is failing. A visual scan of all commits shows them all as signed off.

**Review by lholmquist — APPROVED** [review]
Once those other commits are added,  then LGTM

**Comment by lholmquist** [comment]
> Can't quite figure out why DCO check is failing. A visual scan of all commits shows them all as signed off.

The check is complaing about this commit:

https://github.com/cloudevents/sdk-javascript/pull/336/commits/8ac3eb0c69d980a4475052ce3f102b8b88602fa5

**Comment by lance** [comment]
@lholmquist I see it complaining about this one https://github.com/cloudevents/sdk-javascript/pull/336/commits/f3953a9a5abf5c0267247f9939cf567a47eccd91. I just set that DCO check to pass manually, since a review of the commit message shows that it has been signed off.

**Comment by lance** [comment]
@cloudevents/sdk-javascript-maintainers I think we should be ready to drop a v3.2.0 release. GTG?

**Comment by lholmquist** [comment]
LGTM

**Comment by lholmquist** [comment]
@lance when you do merge this,  don't hit "Squash and Merge" :)

**Pull request merged**
