### PR TITLE
test: implement the cucumber conformance tests

### PR DESCRIPTION
**Pull request by lance**
Fixes: https://github.com/cloudevents/sdk-javascript/issues/71

Items remaining

- [x] use `git submodule` to pull in the features from cloudevents/spec
- [x] investigate why time stamps are not identical
- [x] investigate why datacontenttype is not identical
- [x] validate event data

### CODE REVIEW

**Comment by lance** [comment]
@helio-frota that's a good suggestion. I didn't realize you could provide a URL. Definitely better than pulling in a submodule

**Comment by lance** [comment]
@helio-frota I have not been able to make your suggestion work. Unclear why. :man_shrugging:

**Comment by helio-frota** [comment]
@lance that was a false positive : ( the submodule was here, and when running pointing to a remote file, the cucumber falls back to the local file in the disk. Sorry.

But to try to remedy that I have created a small package called `downtotemp` and you can try using this way:

```
"conformance": "npx downtotemp https://raw.githubusercontent.com/cloudevents/conformance/master/features/http-protocol-binding.feature && cucumber-js /tmp/http-protocol-binding.feature -p default",
```

It is working least.

**Comment by lance** [comment]
@cloudevents/sdk-javascript-maintainers PTAL

@helio-frota thanks for the suggestions - done.

**Comment by lance** [comment]
Ping @cloudevents/sdk-javascript-maintainers ptal

**Comment by lance** [comment]
@lholmquist it's mainly to keep the integration tests separate from the conformance steps that are now in `test/conformance`. I'm not sure how much trouble that merge will be. I imagine it won't be a problem, but :shrug:

**Pull request merged**
