### PR TITLE
feat: use npm name cloudevents

### LINKED ISSUE #215: npm i cloudevents
We should make it really as simple as possible to use this module.

## Expected

```
npm i cloudevents
```

## Actual

```
npm install cloudevents-sdk
```

Not sure who's publishing the npm module, happy to give `cloudevents` for publishing source in this repo.

Python, Ruby, C# all don't use `cloudevents-sdk`, just `cloudevents`.

### PR DESCRIPTION
**Pull request by grant**
Prepares for naming npm package `cloudevents`.
Fixes #215.

BREAKING CHANGE

### CODE REVIEW

**Comment by lance** [comment]
Looks like you have some conflicts with `master`. Can you fix those?

**Comment by grant** [comment]
> Looks like you have some conflicts with `master`. Can you fix those?

I can't see the conflicts. Can you comment on the conflicts in the diff?

**Comment by lance** [comment]
I haven't looked at the diff, I'm just looking at the merge button in the PR.

> This branch cannot be rebased due to conflicts
> Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

**Comment by grant** [comment]
Can you take a picture of what you see?

This is what I see:

Screen Shot 2020-07-23 at 15 42 12

**Comment by lance** [comment]
Strange...

image

**Comment by grant** [comment]
Strange indeed.
Do you want to approve this +5 −5 diff PR?
I can merge.

Screen Shot 2020-07-23 at 16 10 28

**Pull request merged**
