### PR TITLE
fix: support mTLS in 1.0 Binary and Structured emitters

### PR DESCRIPTION
**Pull request by lance**
This commit modifies both of the 1.0 emitters so that they may
accept typed objects as a part of the configuration. When using
mTLS in Node, you need to provide an `Agent` to the underlying
HTTP handler. In this case, Axios will pass this object along to
Node.js when it is provided.

Note: This does not address the issue in 0.3 or below.

Fixes: https://github.com/cloudevents/sdk-javascript/issues/48

Signed-off-by: Lance Ball <lball@redhat.com>

### CODE REVIEW

**Comment by fabiojose** [comment]
@lance, please sign off the commits.

**Comment by lance** [comment]
Hi @fabiojose. I originally pushed with no signoff. But then amended the commit and force pushed to the branch, but the check didn’t rerun. If you look at the commit, it has been signed off. https://github.com/cloudevents/sdk-javascript/commit/3a063d72451d1156df8fe9c3499ef1e81e905060

**Comment by fabiojose** [comment]
@lance, please fill the CHANGELOG.md with those changes and the warning about <0.3 support.

**Comment by lance** [comment]
@fabiojose anything else you are interested in seeing here?

**Comment by fabiojose** [comment]
LGTM

**Pull request merged**
