### PR TITLE
Version parsers

### PR DESCRIPTION
**Pull request by grant**
## Proposed Changes

- Simplify parsers
- Remove duplicate code
- Reduces file count/complexity over versioning

## Description

- Fixes Issue #273 (partially)

### CODE REVIEW

**Comment by helio-frota** [comment]
@grant I'm not sure but my view on that is you are trying to "consolidate versions for the future" that approach is good so :+1: to that. So for what I understood when a new v.x spec come out the project has the structure to add the things without much effort or something (?) also centralizing things in versions.ts ?

In other hand @lance's comment makes sense. So my question is your PR wording not accurate meaning or something ?

anyway I'm trying to get the point

**Comment by helio-frota** [comment]
>  I prefer to have code for each version in a distinct file. Not sure how others feel about this.

@lance I have no idea how many times and how often new versions will be created/added. The approach looks good to me but not sure about the benefit related with the occurrence of the future changes/additions in versions.

:+1:

**Comment by grant** [comment]
The `PassThroughParser` is not stateful and can be reused. It really should be static like I believe most every other function in this library.

Is there something you'd like me to change?

**Comment by lholmquist** [comment]
I don't have any strong feelings on keeping things separate.  ATM, since there are only 2 versions, it probably doesn't matter combining them.

**Comment by lance** [comment]
> Is there something you'd like me to change?

Not necessarily - was just trying to have some conversation around these questions.

**Comment by grant** [comment]
To be clear, I saw a lot of improvements beyond this, but I'd never finish a concrete PR if I went chasing them.

**Pull request merged**
