### PR TITLE
fix: do not alter an event's data attribute

### PR DESCRIPTION
**Pull request by lance**
## Proposed Changes

- Change `CloudEvent` so that it never modifies the `data` attribute
- If an event's `datacontenttype` property is a content type that we don't support, just set the data attribute - don't throw

## Description

When setting an event's data attribute we were trying to be really clever and this is problematic. Instead, keep the data attribute unchanged. Per the 1.0 specification, the data attribute is still inspected to determine if it is binary data, and if so, a data_base64 attribute is added with the contents of the data property encoded as base64.

Fixes: https://github.com/cloudevents/sdk-javascript/issues/343

Signed-off-by: Lance Ball <lball@redhat.com>

### CODE REVIEW

**Review by grant — APPROVED** [review]

**Review by lholmquist — APPROVED** [review]

**Comment by lance** [comment]
Do not merge. I have found a bug in this implementation that I need to fix.

**Comment by lance** [comment]
@cloudevents/sdk-javascript-maintainers there is an interesting discussion in Slack around this question of binary data: https://cloud-native.slack.com/archives/C9DB5ABAA/p1601416717013400

**Comment by lance** [comment]
@cloudevents/sdk-javascript-maintainers PTAL - thanks

**Review by grant — APPROVED** [review]
Not modifying the data is great.
I think we'll talk about base64 data a bit more in the weekly SDK call too.

**Review by lholmquist — APPROVED** [review]

**Comment by lance** [comment]
Based on the discussion in today's CNCF call, I am going to remove this test and the associated functionality.

https://github.com/cloudevents/sdk-javascript/blob/5255a19ea458ab6bd9854a42fbc83fe59b2a783f/test/integration/message_test.ts#L190-L195

**Pull request merged**
