### PR TITLE
feat: implementation of discovery spec

### PR DESCRIPTION
**Pull request by loopingz**
See: https://github.com/cloudevents/spec/blob/master/discovery.md

This PR still need the unit testing but it is pushed for discussion in our weekly call

### CODE REVIEW

**Comment by lance** [comment]
@loopingz are you planning to do some refactoring to make this pr include a monorepo with multiple packages? I believe this is what we discussed last week or so but now am not sure. Thanks

**Comment by loopingz** [comment]
Yes but not in this PR we can either close it or keep it for reference for now

**Comment by lance** [comment]
> Yes but not in this PR we can either close it or keep it for reference for now

I'm fine keeping it open as a WIP for now. Just wanted to be sure I knew what was going on with it.

**Review by grant — COMMENTED** [review]
(Reviewing PRs in this repo)

I'm fine closing this open draft PR for now. We can always re-open.
Thoughts @lance?

**Comment by lance** [comment]
@loopingz this PR and https://github.com/cloudevents/sdk-javascript/pull/365 have both kind of just languished over the last year. I'm happy to collaborate on realizing the intent if you would like to move forward with them. Although, I do agree that https://github.com/cloudevents/sdk-javascript/pull/365 should probably live in its own repository - or exist as a major refactor of this one into a multi-project meta-repo. But I digress.... for now, I think @grant is probably right about both of these (thanks @grant for the renewed triage work!). Let's close them and, if you'd like to renew discussion and/or collaboration around this effort we can either reopen or initiate a new effort. Thanks for the work you did here!

**Comment by loopingz** [comment]
@lance @grant agreed 👍 thanks for the clean up work

**Pull request closed without merging**
