### PR TITLE
The start of JavaScript SDK

### PR DESCRIPTION
**Pull request by fabiojose**
Take a look in the this project start.

### CODE REVIEW

**Comment by duglin** [comment]
ping @ac360

**Comment by fabiojose** [comment]
Hey @ac360 , what do you about this proposal of impl. ?

**Comment by fabiojose** [comment]
@duglin?

**Comment by duglin** [comment]
@fabiojose feel free to merge

**Comment by fabiojose** [comment]
> @fabiojose feel free to merge

Good, but I do not have permission to do that!

**Comment by duglin** [comment]
sorry, I thought I already did that - try now

**Comment by duglin** [comment]
ping me on cncf's slack

**Comment by duglin** [comment]
did you accept the invite to join the sdk-maintainers?

**Comment by fabiojose** [comment]
> sdk-maintainers

Well, I did not receive! Could you send again please?

**Pull request merged**
